// Code generated by scripts/gen-scalar-accessors.sh -- DO NOT EDIT.

package tomledit

import "time"

// The Scalar accessor family, per node kind. Every method is one call to the
// shared staged accessor, which asks the conversion table what this node's
// value converts into; the family's rules are documented on the Scalar
// interface, and the stages on asValue.

// AsString reads the node through the conversion table.
func (n *StringNode) AsString() (string, error) { return nodeAs[string](n) }

// AsInt reads the node through the conversion table.
func (n *StringNode) AsInt() (int64, error) { return nodeAs[int64](n) }

// AsFloat reads the node through the conversion table.
func (n *StringNode) AsFloat() (float64, error) { return nodeAs[float64](n) }

// AsBool reads the node through the conversion table.
func (n *StringNode) AsBool() (bool, error) { return nodeAs[bool](n) }

// AsTime reads the node through the conversion table.
func (n *StringNode) AsTime() (time.Time, error) { return nodeAs[time.Time](n) }

// AsLocalDateTime reads the node through the conversion table.
func (n *StringNode) AsLocalDateTime() (LocalDateTime, error) { return nodeAs[LocalDateTime](n) }

// AsLocalDate reads the node through the conversion table.
func (n *StringNode) AsLocalDate() (LocalDate, error) { return nodeAs[LocalDate](n) }

// AsLocalTime reads the node through the conversion table.
func (n *StringNode) AsLocalTime() (LocalTime, error) { return nodeAs[LocalTime](n) }

// AsString reads the node through the conversion table.
func (n *IntegerNode) AsString() (string, error) { return nodeAs[string](n) }

// AsInt reads the node through the conversion table.
func (n *IntegerNode) AsInt() (int64, error) { return nodeAs[int64](n) }

// AsFloat reads the node through the conversion table.
func (n *IntegerNode) AsFloat() (float64, error) { return nodeAs[float64](n) }

// AsBool reads the node through the conversion table.
func (n *IntegerNode) AsBool() (bool, error) { return nodeAs[bool](n) }

// AsTime reads the node through the conversion table.
func (n *IntegerNode) AsTime() (time.Time, error) { return nodeAs[time.Time](n) }

// AsLocalDateTime reads the node through the conversion table.
func (n *IntegerNode) AsLocalDateTime() (LocalDateTime, error) { return nodeAs[LocalDateTime](n) }

// AsLocalDate reads the node through the conversion table.
func (n *IntegerNode) AsLocalDate() (LocalDate, error) { return nodeAs[LocalDate](n) }

// AsLocalTime reads the node through the conversion table.
func (n *IntegerNode) AsLocalTime() (LocalTime, error) { return nodeAs[LocalTime](n) }

// AsString reads the node through the conversion table.
func (n *FloatNode) AsString() (string, error) { return nodeAs[string](n) }

// AsInt reads the node through the conversion table.
func (n *FloatNode) AsInt() (int64, error) { return nodeAs[int64](n) }

// AsFloat reads the node through the conversion table.
func (n *FloatNode) AsFloat() (float64, error) { return nodeAs[float64](n) }

// AsBool reads the node through the conversion table.
func (n *FloatNode) AsBool() (bool, error) { return nodeAs[bool](n) }

// AsTime reads the node through the conversion table.
func (n *FloatNode) AsTime() (time.Time, error) { return nodeAs[time.Time](n) }

// AsLocalDateTime reads the node through the conversion table.
func (n *FloatNode) AsLocalDateTime() (LocalDateTime, error) { return nodeAs[LocalDateTime](n) }

// AsLocalDate reads the node through the conversion table.
func (n *FloatNode) AsLocalDate() (LocalDate, error) { return nodeAs[LocalDate](n) }

// AsLocalTime reads the node through the conversion table.
func (n *FloatNode) AsLocalTime() (LocalTime, error) { return nodeAs[LocalTime](n) }

// AsString reads the node through the conversion table.
func (n *BooleanNode) AsString() (string, error) { return nodeAs[string](n) }

// AsInt reads the node through the conversion table.
func (n *BooleanNode) AsInt() (int64, error) { return nodeAs[int64](n) }

// AsFloat reads the node through the conversion table.
func (n *BooleanNode) AsFloat() (float64, error) { return nodeAs[float64](n) }

// AsBool reads the node through the conversion table.
func (n *BooleanNode) AsBool() (bool, error) { return nodeAs[bool](n) }

// AsTime reads the node through the conversion table.
func (n *BooleanNode) AsTime() (time.Time, error) { return nodeAs[time.Time](n) }

// AsLocalDateTime reads the node through the conversion table.
func (n *BooleanNode) AsLocalDateTime() (LocalDateTime, error) { return nodeAs[LocalDateTime](n) }

// AsLocalDate reads the node through the conversion table.
func (n *BooleanNode) AsLocalDate() (LocalDate, error) { return nodeAs[LocalDate](n) }

// AsLocalTime reads the node through the conversion table.
func (n *BooleanNode) AsLocalTime() (LocalTime, error) { return nodeAs[LocalTime](n) }

// AsString reads the node through the conversion table.
func (n *DateTimeNode) AsString() (string, error) { return nodeAs[string](n) }

// AsInt reads the node through the conversion table.
func (n *DateTimeNode) AsInt() (int64, error) { return nodeAs[int64](n) }

// AsFloat reads the node through the conversion table.
func (n *DateTimeNode) AsFloat() (float64, error) { return nodeAs[float64](n) }

// AsBool reads the node through the conversion table.
func (n *DateTimeNode) AsBool() (bool, error) { return nodeAs[bool](n) }

// AsTime reads the node through the conversion table.
func (n *DateTimeNode) AsTime() (time.Time, error) { return nodeAs[time.Time](n) }

// AsLocalDateTime reads the node through the conversion table.
func (n *DateTimeNode) AsLocalDateTime() (LocalDateTime, error) { return nodeAs[LocalDateTime](n) }

// AsLocalDate reads the node through the conversion table.
func (n *DateTimeNode) AsLocalDate() (LocalDate, error) { return nodeAs[LocalDate](n) }

// AsLocalTime reads the node through the conversion table.
func (n *DateTimeNode) AsLocalTime() (LocalTime, error) { return nodeAs[LocalTime](n) }

// AsString reads the node through the conversion table.
func (n *LocalDateTimeNode) AsString() (string, error) { return nodeAs[string](n) }

// AsInt reads the node through the conversion table.
func (n *LocalDateTimeNode) AsInt() (int64, error) { return nodeAs[int64](n) }

// AsFloat reads the node through the conversion table.
func (n *LocalDateTimeNode) AsFloat() (float64, error) { return nodeAs[float64](n) }

// AsBool reads the node through the conversion table.
func (n *LocalDateTimeNode) AsBool() (bool, error) { return nodeAs[bool](n) }

// AsTime reads the node through the conversion table.
func (n *LocalDateTimeNode) AsTime() (time.Time, error) { return nodeAs[time.Time](n) }

// AsLocalDateTime reads the node through the conversion table.
func (n *LocalDateTimeNode) AsLocalDateTime() (LocalDateTime, error) { return nodeAs[LocalDateTime](n) }

// AsLocalDate reads the node through the conversion table.
func (n *LocalDateTimeNode) AsLocalDate() (LocalDate, error) { return nodeAs[LocalDate](n) }

// AsLocalTime reads the node through the conversion table.
func (n *LocalDateTimeNode) AsLocalTime() (LocalTime, error) { return nodeAs[LocalTime](n) }

// AsString reads the node through the conversion table.
func (n *LocalDateNode) AsString() (string, error) { return nodeAs[string](n) }

// AsInt reads the node through the conversion table.
func (n *LocalDateNode) AsInt() (int64, error) { return nodeAs[int64](n) }

// AsFloat reads the node through the conversion table.
func (n *LocalDateNode) AsFloat() (float64, error) { return nodeAs[float64](n) }

// AsBool reads the node through the conversion table.
func (n *LocalDateNode) AsBool() (bool, error) { return nodeAs[bool](n) }

// AsTime reads the node through the conversion table.
func (n *LocalDateNode) AsTime() (time.Time, error) { return nodeAs[time.Time](n) }

// AsLocalDateTime reads the node through the conversion table.
func (n *LocalDateNode) AsLocalDateTime() (LocalDateTime, error) { return nodeAs[LocalDateTime](n) }

// AsLocalDate reads the node through the conversion table.
func (n *LocalDateNode) AsLocalDate() (LocalDate, error) { return nodeAs[LocalDate](n) }

// AsLocalTime reads the node through the conversion table.
func (n *LocalDateNode) AsLocalTime() (LocalTime, error) { return nodeAs[LocalTime](n) }

// AsString reads the node through the conversion table.
func (n *LocalTimeNode) AsString() (string, error) { return nodeAs[string](n) }

// AsInt reads the node through the conversion table.
func (n *LocalTimeNode) AsInt() (int64, error) { return nodeAs[int64](n) }

// AsFloat reads the node through the conversion table.
func (n *LocalTimeNode) AsFloat() (float64, error) { return nodeAs[float64](n) }

// AsBool reads the node through the conversion table.
func (n *LocalTimeNode) AsBool() (bool, error) { return nodeAs[bool](n) }

// AsTime reads the node through the conversion table.
func (n *LocalTimeNode) AsTime() (time.Time, error) { return nodeAs[time.Time](n) }

// AsLocalDateTime reads the node through the conversion table.
func (n *LocalTimeNode) AsLocalDateTime() (LocalDateTime, error) { return nodeAs[LocalDateTime](n) }

// AsLocalDate reads the node through the conversion table.
func (n *LocalTimeNode) AsLocalDate() (LocalDate, error) { return nodeAs[LocalDate](n) }

// AsLocalTime reads the node through the conversion table.
func (n *LocalTimeNode) AsLocalTime() (LocalTime, error) { return nodeAs[LocalTime](n) }
