#!/usr/bin/env bash
#
# Generate the per-node-type forwarders of the Scalar accessor family.
#
# The As* family is declared on the Scalar interface, so every value-carrying
# node kind must implement all of it. Each implementation is the same one line
# -- a call to the one shared staged accessor -- and Go has no way to write that
# line once: a method on the embedded base cannot see the node it was promoted
# onto, and the shared accessor needs the node itself to ask the conversion
# table what kind of value it carries. So the forwarders are generated here
# rather than hand-maintained, and a node kind or an accessor added to the
# family is one edit to the lists below.
#
# Usage:
#   scripts/gen-scalar-accessors.sh --print          # write the file to stdout
#   scripts/gen-scalar-accessors.sh --write PATH     # write it to PATH
#
# Exactly one of the two is required; there is no default.

set -euo pipefail

# The value-carrying node kinds, in the order node.go declares them.
NODES=(
	StringNode
	IntegerNode
	FloatNode
	BooleanNode
	DateTimeNode
	LocalDateTimeNode
	LocalDateNode
	LocalTimeNode
)

# The accessor family, as METHOD:GO-TYPE pairs, in the order the Scalar
# interface declares them.
ACCESSORS=(
	AsString:string
	AsInt:int64
	AsFloat:float64
	AsBool:bool
	AsTime:time.Time
	AsLocalDateTime:LocalDateTime
	AsLocalDate:LocalDate
	AsLocalTime:LocalTime
)

emit() {
	cat <<'EOF'
// Code generated by scripts/gen-scalar-accessors.sh -- DO NOT EDIT.

package tomledit

import "time"

// The Scalar accessor family, per node kind. Every method is one call to the
// shared staged accessor, which asks the conversion table what this node's
// value converts into; the family's rules are documented on the Scalar
// interface, and the stages on asValue.
EOF

	for node in "${NODES[@]}"; do
		echo
		for pair in "${ACCESSORS[@]}"; do
			method="${pair%%:*}"
			gotype="${pair#*:}"
			printf '// %s reads the node through the conversion table.\n' "$method"
			printf 'func (n *%s) %s() (%s, error) { return nodeAs[%s](n) }\n' \
				"$node" "$method" "$gotype" "$gotype"
		done
	done
}

case "${1:-}" in
--print)
	emit
	;;
--write)
	out="${2:-}"
	if [ -z "$out" ]; then
		echo "usage: $0 --write PATH" >&2
		exit 2
	fi
	emit >"$out"
	gofmt -w "$out"
	echo "wrote $out"
	;;
*)
	echo "usage: $0 (--print | --write PATH)" >&2
	exit 2
	;;
esac
